### ISSUE TITLE
Override client settings

### ISSUE THREAD

**Issue by Sumsun93** [saltminede/saltychat-docs#10]
Hi,

Is it possible to add option to override client plugin settings from client-side?

**Comment by BlackFlash5** [comment]
It is possible to add this, but most likely not gonna happen, because developers can override user settings as they please.
Some people need certain settings to hear properly and with 1.2.0+ we added an easy way to set some options, so they don't have to fiddle around with a json config file.
Through the TeamSpeak UI you can also edit all options during the runtime.
